// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Js_json = require("bs-platform/lib/js/js_json.js");

function get(str, f) {
  chrome.storage.local.get(str, (function (dict) {
          return Curry._1(f, Js_dict.map(Js_json.classify, dict));
        }));
  
}

function getMany(arr, f) {
  chrome.storage.local.get(arr, (function (dict) {
          return Curry._1(f, Js_dict.map(Js_json.classify, dict));
        }));
  
}

var Local = {
  get: get,
  getMany: getMany
};

exports.Local = Local;
/* No side effect */
