// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Chrome = require("../lib/Chrome.bs.js");

window.onload = (function () {
    alert("aa");
    alert("bb");
    window.document.getElementById("root");
    return Chrome.Local.get("data", (function (v) {
                  console.log(v);
                  
                }));
  });

/*  Not a pure module */
