// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "../../node_modules/bs-platform/lib/es6/belt_Array.js";

window.onload = (function () {
    var el = window.document.getElementById("root");
    chrome.storage.local.get("data", (function (value) {
            console.log(value.data);
            var data = value.data;
            return Belt_Array.forEach(data, (function (d) {
                          var list = window.document.createElement("li");
                          list.innerHTML = d.itemName;
                          console.log(el);
                          console.log(list);
                          el.appendChild(list);
                          
                        }));
          }));
    var btn = window.document.getElementById("create-receipt");
    console.log(btn);
    btn.addEventListener("click", (function (param) {
            chrome.storage.local.get("data", (function (value) {
                    var data = value.data;
                    chrome.runtime.sendMessage({
                          method: "postRequest",
                          value: data
                        }, (function (id) {
                            window.open("https://receipten.web.app/#/item/" + id);
                            
                          }));
                    
                  }));
            
          }));
    
  });

export {
  
}
/*  Not a pure module */
